matrix:
  controlsign: '!'
  homeserver: https://chat.example.org
  username: '@spacebot:example.org'
  password: 'THIS_IS_THE_MATRIX_USER_PASSWORD'
  rooms:
    - '!ABCDEFGHIJKLMNOPQR:chat.example.org'
  sessioncache: config/cache/matrix-session
plugins:
  amtsblatt:
    # Timestamp from last announced item
    published: 0
    # Restrict automatic announcement of new "Amtsblatt" to room
    rooms:
      - '!ABCDEFGHIJKLMNOPQR:chat.example.org'
    # RSS feed
    rss: https://www.erfurt.de/ef/de/service/rss/amtsblatt.rss
  dates:
    # Intervals for auto announce in minutes
    announce_interval:
      - 60
      - 1440
    # Calendar definitions
    calendar:
      - id: calendar1
        name: First calender
        url: https://calendar.example.org/calendar_1.ical
      - id: calendar2
        name: Second calender
        url: https://calendar.example.org/calendar_2.ical
        # Restrict automatic announcement of events to room
        rooms:
          - '!ABCDEFGHIJKLMNOPQR:chat.example.org'
    # Configure format for output
    format:
      datetime: '%d.%m.%Y %H:%M'
    # Restrict output of events for the couple of days
    list_days: 21
  rss:
    # Number of items in output
    count:
      # Merged feeds
      merged: 1
      # Single feeds
      single: 3
    feeds:
    - id: wiki
      name: Wiki
      # Timestamp from last announced item, will be set to now on first start
      # published: 0
      # Restrict automatic announcement of rss feed entries to room
      rooms:
      - '!ABCDEFGHIJKLMNOPQR:chat.example.org'
      # Optional type of rss feed (dokuwiki, wordpress or unset)
      type: dokuwiki
      url: https://wiki.example.org/feed.php
    - id: blog
      name: Blog
      type: wordpress
      url: https://example.org/feed/
  time:
    locale: de_DE
