matrix:
  controlsign: '!'
  homeserver: https://chat.example.org
  username: '@spacebot:example.org'
  password: 'THIS_IS_THE_MATRIX_USER_PASSWORD'
  rooms:
    - '!ABCDEFGHIJKLMNOPQR:chat.example.org'
  sessioncache: config/cache/matrix-session
plugins:
  amtsblatt:
    _enabled: true
    # Timestamp from last announced item
    published: 0
    # Restrict automatic announcement of new "Amtsblatt" to room
    rooms:
      - '!ABCDEFGHIJKLMNOPQR:chat.example.org'
    # RSS feed
    rss: https://www.erfurt.de/ef/de/service/rss/amtsblatt.rss
  dates:
    _enabled: true
    # Intervals for auto announce in minutes
    announce_interval:
      - 60
      - 1440
    # Calendar definitions
    calendar:
      - id: calendar1
        name: First calender
        url: https://calendar.example.org/calendar_1.ical
      - id: calendar2
        name: Second calender
        url: https://calendar.example.org/calendar_2.ical
        # Restrict automatic announcement of events to room
        rooms:
          - '!ABCDEFGHIJKLMNOPQR:chat.example.org'
        # Optional calendar individual intervals for auto announce in minutes
        # announce_interval:
        #   - 15
        #   - 45
        # Limit entries on command (optional)
        # limit_entries: 4
        # Announce location (optional)
        # announce_location: true
        # Calender format (ical - default, xcal)
        # type: ical
    # Configure format for output
    format:
      datetime: '%d.%m.%Y %H:%M'
    # Restrict output of events for the couple of days
    list_days: 21
  mowas:
    _enabled: true
    # Configure format for output
    format:
      datetime: '%d.%m.%Y %H:%M'
    # Location definitions
    locations:
    - id: erfurt
      name: Erfurt
      # Amtlicher Regionalschluessl (ARS) for location
      # see https://www.xrepository.de/details/urn:de:bund:destatis:bevoelkerungsstatistik:schluessel:rs_2021-01-31
      ars: '160510000000'
      # Announce high water occurrences
      highwater: true
      # Announce weather occurrences
      weather: true
      # Restrict automatic announcement of new occurrences to room
      rooms:
      - '!ABCDEFGHIJKLMNOPQR:chat.example.org'
  now:
    _enabled: true
    locale: de_DE
  rss:
    _enabled: true
    # Number of items in output
    count:
      # Merged feeds
      merged: 1
      # Single feeds
      single: 3
    feeds:
    - id: wiki
      name: Wiki
      # Run only every 4 hours on random minute
      cron: 'R */4 * * *'
      # Timestamp from last announced item, will be set to now on first start
      # published: 0
      # Restrict automatic announcement of rss feed entries to room
      rooms:
      - '!ABCDEFGHIJKLMNOPQR:chat.example.org'
      # Summarize changes (print titles and summarize link)
      summarize:
        # Link to changelog
        link: https://wiki.example.org/?do=recent
        # Minimal treshold for number of entries which are NOT summarized
        treshold: 1
      # Optional type of rss feed (dokuwiki, wordpress or unset)
      type: dokuwiki
      url: https://wiki.example.org/feed.php
    - id: blog
      name: Blog
      type: wordpress
      url: https://example.org/feed/
  status:
    _enabled: true
    # Cache interval
    cache_interval: 60
    # Show people present
    show_people: false
    status:
    - id: examplespace
      url: https://status.example.org/status.json
      # Restrict command response to room
      rooms:
      - '!ABCDEFGHIJKLMNOPQR:chat.example.org'
